name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily at 12 AM UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka        # Must match your <!--START_SECTION:waka-->
          SHOW_TITLE: true          # optional, shows "WakaTime Stats"
          TIME_RANGE: all_time      # options: last_7_days, last_30_days, last_6_months, last_year, all_time
          SHOW_TOTAL: true          # optional, shows total coding time
          LANG_COUNT: 5             # optional, top 5 languages
