name: Waka Readme

on:
  workflow_dispatch:   # allows manual trigger
  schedule:
    - cron: "0 0 * * *" # daily at 12:00 AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}              # required to commit
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          REPOSITORY: hanlynn-aung/hanlynn-aung         # your repo
          TARGET_PATH: README.md
          SECTION_NAME: waka
          SHOW_TITLE: true
          TIME_RANGE: last_7_days                        # weekly stats
          BLOCKS: "->"
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML
          COMMIT_MESSAGE: "Updated WakaTime weekly graph"
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: Han Lynn Aung
          AUTHOR_EMAIL: hanlynnaung1997@gmail.com
