name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at UTC midnight
  workflow_dispatch:

jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch WakaTime Stats
        run: |
          curl -o waka_weekly.svg "https://wakatime.com/share/@hanlynn-aung/weekly.svg"
      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add waka_weekly.svg
          git commit -m "Update WakaTime weekly stats"
          git push
